# -*- coding: utf-8 -*-
"""My_Class.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdfTaqa4jzlCpM7fC2MesMuxOhU94Xod
"""

#create class with multi functions
class My_Class:

#function to list out AI subfields
  def SubfieldsInAI():
    AI_list=['Machine Learning','Neural Networks','Vision','Robotics','Speech processing','Natural Language Processing']
    for list in AI_list:
      print(list)

#function that checks whether the given number is Odd or Even
  def OddEven():
    getinput=int(input("Enter a number: "))
    if (getinput%2==0):
      result=print(getinput,"is even")
      return result
    else:
      result=print(getinput,"is odd")
      return result

#function that tells elegibility of marriage for male and female according to their age limit : 21 for male and 18 for female
  def marriage_elegibility():
    getgender=str(input("Enter your gender: "))
    getage=int(input("Enter your age: "))
    if(getgender=="female" and getage>=18):
      result=print("You are eligible")
      return result
    elif(getgender=="male" and getage>=21):
      result=print("You are eligible")
      return result
    else:
      result=print("You are not eligible")
      return result

#function to calculate the percentage of your 10th mark
  def calculate_percentage():
# Input marks for 5 subjects
    marks = [ ]
    for i in range(1, 6):
      mark = float(input(f"Subject {i}: "))
      marks.append(mark)
# Calculate total and percentage
    total_marks = sum(marks)
    percentage = (total_marks / 500) * 100
    print("Total Marks: ",total_marks)
    print("Percentage: ",percentage)

#calculate area and perimeter or triangle using class and function
  def triangle_Calc():
    calc=input("Calculate Area or Perimeter?: ")
    if (calc=="Area"):
      Height=int(input("Height: "))
      Breadth=int(input("Breadth:"))
      Area=(Height*Breadth)/2
      area_result=print("Area of Triangle: ",Area)
      return(area_result)
    elif (calc=="Perimeter"):
      Height1=int(input("Height1: "))
      Height2=int(input("Height2: "))
      Breadth=int(input("Breadth:"))
      Perimeter=Height1+Height2+Breadth
      peri_result=print("Perimeter of Triangle: ",Perimeter)
      return(peri_result)
    else:
      no_result=print("Invalid choice. Please enter 'Area' or 'Perimeter'.")
      return(no_result)

My_Class.SubfieldsInAI()

My_Class.OddEven()

My_Class.marriage_elegibility()

My_Class.calculate_percentage()

My_Class.triangle_Calc()

